// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// Handler is an autogenerated mock type for the Handler type
type Handler struct {
	mock.Mock
}

// Handle provides a mock function with given fields: err
func (_m *Handler) Handle(err error) {
	_m.Called(err)
}
