linters-settings:
    gci:
        local-prefixes: emperror.dev/emperror
    goimports:
        local-prefixes: emperror.dev/emperror
    golint:
        min-confidence: 0

linters:
    disable-all: true
    enable:
        - bodyclose
        - deadcode
        - dogsled
        - dupl
        - errcheck
        - exhaustive
        - exportloopref
        - gci
        - gochecknoglobals
        - gochecknoinits
        - gocognit
        - goconst
        - gocritic
        - gocyclo
        - godot
        - gofmt
        - gofumpt
        - goimports
        - golint
        - goprintffuncname
        - gosec
        - gosimple
        - govet
        - ineffassign
        - lll
        - misspell
        - nakedret
        - nlreturn
        - noctx
        - nolintlint
        - prealloc
        - rowserrcheck
        - scopelint
        - sqlclosecheck
        - staticcheck
        - structcheck
        - stylecheck
        - typecheck
        - unconvert
        - unparam
        - unused
        - varcheck
        - whitespace

        # unused
        # - depguard
        # - goheader
        # - gomodguard

        # don't enable:
        # - asciicheck
        # - funlen
        # - godox
        # - goerr113
        # - gomnd
        # - interfacer
        # - maligned
        # - nestif
        # - testpackage
        # - wsl

issues:
    exclude-rules:
        -   text: "SA1029: should not use built-in type string as key for value; define your own type to avoid collisions"
            linters:
                - staticcheck
